services:
  - type: web
    name: books-cravd
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: books_cravd_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: true
    plan: free
    region: singapore
    branch: main
    healthCheckPath: /
    buildFilter:
      paths:
      - "**/*.rb"
      - "**/*.erb"
      - "**/*.js"
      - "**/*.css"
      - "Gemfile.lock"
      - "config/**/*"
      - "bin/*"

databases:
  - name: books_cravd_db
    ipAllowList: []
    plan: free